# Generated by Django 2.2.4 on 2019-08-03 16:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('coverImage', models.ImageField(blank=True, upload_to=blog.models.get_image_path)),
                ('summary', models.TextField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-is_published', '-date_published', '-date_created'],
            },
        ),
    ]
