# Generated by Django 2.2.4 on 2019-09-01 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190822_2022'),
        ('blog', '0011_auto_20190822_2139'),
    ]

    operations = [
    ]
