# Generated by Django 2.2.4 on 2019-09-02 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190902_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_published', '-date_published', '-date_created'], 'permissions': [('can_change_post_is_published', 'Can publish post')]},
        ),
    ]
