# Generated by Django 2.2.3 on 2019-11-05 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190902_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_published', '-date_published', '-date_created'], 'permissions': [('can_publish', 'Can publish post')]},
        ),
    ]
